### ISSUE TITLE
Backport request of 'XtremIO: fix fetching FC targets from X2 array'

### ISSUE THREAD

**Issue by knoha-rh** [emc-openstack/xtremio-cinder-driver#6]
Current xtremio-cinder-driver has an issue described in the upstream cinder launchpad, https://bugs.launchpad.net/cinder/+bug/1702458.

Some users in Kilo hit the issue and the commit should be backported.
~~~
commit 67facebe4d9996bcbe8b3aaffd0a0d78660649e7
Author: Shay Halsband <shay.halsband@emc.com>
Date:   Mon Jul 3 15:48:22 2017 +0300

    XtremIO: fix fetching FC targets from X2 array
    
    Previous versions of XtremIO had the type as part of the target name, in
    X2 this convention was changed and a driver updated is required to query
    the type from the target object.
    
    Closes-Bug: #1702458
    Change-Id: Ie62d7bc84b8b0e54ff627a52763e93456ff45d65
~~~

Could you backport the fix into this kilo driver?

**Comment by shayh** [comment]
we'll work on this, for now as a work around you can rename the FC Targets using XMS CLI 
as an example for target 3 
`rename tg-id=3 new-name="X1-SC1-fc3"`

**Comment by knoha-rh** [comment]
Hello,

Thanks for the update and suggesting the workaround.
We'll wait for the work of this issue.

Thanks,
Keigo
